# Generated by Django 5.2.11 on 2026-04-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('category', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('price', models.FloatField(default=0)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
