# Generated by Django 5.2.11 on 2026-04-19 14:31

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='location',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('hall_a', 'Hall A'), ('hall_b', 'Hall B'), ('auditorium', 'Auditorium')], max_length=30),
        ),
        migrations.AddField(
            model_name='entry',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='entry',
            name='patient_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='entry',
            name='product_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='entry',
            name='slot',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('student', 'Student'), ('patient', 'Patient'), ('product', 'Product'), ('event', 'Event'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='entry',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
